services:
  - type: web
    name: eventflow-project
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EVENTFLOW_SECRET_KEY
        generateValue: true
